swagger: "2.0"
info:
  description: This is the swagger file that goes with our server code
  version: "1.0.0"
  title: Swagger ReST Article
consumes:
  - application/json
produces:
  - application/json

basePath: /scientificcalculator
paths:
 /src/driver/scientific_calc/ScientificCalc/{pow_value}:
    get:
      operationId: src.driver.scientific_calc.ScientificCalc.cal_power_ten
      tags:
        - ten_power_y
      summary: Calculate value for ten power x
      description: Calculate value for ten power x
      parameters:
        - name: pow_value
          in: path
          description: Provides x value
          type: integer
          required: true
      responses:
        200:
          description: Gives value for ten power x
          schema:
            properties:
              output:
                type: integer